### ISSUE TITLE
Fact collection 2 failed to be processed due to EAP processing error

### ISSUE THREAD

**Issue by syangsao** [quipucords/quipucords#1227]
## Specify type:
- Bug

### Priority:
- High
___

## Description:
Running a full network scan of up to 100 ip addresses fails but creates a detailed report but does not create a summary report

___

### Version Information:
0.0.42

### Expected behavior:
Network scan attempt should complete successfully or give more information on why it fails.

### Actual behavior:
Network scan fails with the following message from reviewing the log file:
~~~
# cat ~/quipucords/log/quipucords.log |grep ERROR
ERROR 2018-04-13 18:50:25,674 model 1166 140290952214272 Job 2 (inspect, elapsed_time: 501s) - Fact collection 2 failed to be processed.
ERROR 2018-04-13 18:50:25,679 model 1166 140290952214272 Job 2 (inspect, elapsed_time: 501s) - STATE UPDATE (failed).  Additional State information: Fact collection 2 failed to be processed.
ERROR 2018-04-13 18:50:25,684 job 1166 140290952214272 AttributeError:'bool' object has no attribute 'splitlines'
~~~

Attempt to create reports from the failed job 
~~~
# qpc report detail --scan-job 2 --json --output-file=~/scan2_detail.json
Report written successfully..
# qpc report summary --scan-job 2 --json --output-file=~/scan2_summary.json
No report summary available for scan job 2.
~~~
### Steps to reproduce:
Ran the following commands to create the scan job
~~~
# qpc cred add --type network --name syangsao --username root --password 
# qpc source add --type network --name syangsao_all --hosts 10.15.108.[1:100]
# qpc scan start --name scan2
# qpc scan job --id 2
{
    "end_time": "2018-04-13T18:50:25.674285",
    "id": 2,
    "options": {
        "max_concurrency": 50
    },
    "report_id": 2,
    "scan": {
        "id": 2,
        "name": "scan2"
    },
    "scan_type": "inspect",
    "sources": [
        {
            "id": 2,
            "name": "syangsao_all",
            "source_type": "network"
        }
    ],
    "start_time": "2018-04-13T18:42:03.738234",
    "status": "failed",
    "status_message": "Fact collection 2 failed to be processed.",
    "systems_count": 100,
    "systems_failed": 76,
    "systems_scanned": 24,
    "tasks": [
        {
            "end_time": "2018-04-13T18:43:00.920051",
            "scan_type": "connect",
            "source": 2,
            "start_time": "2018-04-13T18:42:03.764824",
            "status": "completed",
            "status_message": "Task is complete.",
            "systems_count": 100,
            "systems_failed": 76,
            "systems_scanned": 24
        },
        {
            "end_time": "2018-04-13T18:50:25.424142",
            "scan_type": "inspect",
            "source": 2,
            "start_time": "2018-04-13T18:43:00.927416",
            "status": "completed",
            "status_message": "success",
            "systems_count": 24,
            "systems_failed": 0,
            "systems_scanned": 24
        }
    ]
}
~~~

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | RHV 
Target System   | RHEL             | 5,6,7        | 2.4.6          | RHV, Bare Metal

**Comment by kholdaway** [comment]
@syangsao Can you either slack me the details report or add it here?

Run: `qpc report detail --scan-job 2 --json --output-file=~/scan2_detail.json` and send me that JSON file.

**Comment by syangsao** [comment]
Detail report output is attached

[scan2_detail.json.gz](https://github.com/quipucords/quipucords/files/1908760/scan2_detail.json.gz)

~~~
# qpc report detail --scan-job 2 --json --output-file=~/scan2_detail.json
~~~

**Comment by kholdaway** [comment]
👍

**Comment by syangsao** [comment]
quipucords log is attached

[quipucords.log.gz](https://github.com/quipucords/quipucords/files/1908765/quipucords.log.gz)

**Comment by kholdaway** [comment]
Looks like the EAP processing code needs a guard.
```
  File "/app/quipucords/fingerprinter/__init__.py", line 618, in add_products_to_fingerprint
    eap = detect_jboss_eap(source, raw_fact)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 335, in detect_jboss_eap
    new_presence = call_or_value(fact_dict[PRESENCE], fact_value)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 287, in call_or_value
    return obj(argument)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 192, in is_eap_manifest_version
    for line in manifest.splitlines():
```

**Comment by kholdaway** [comment]
@noahl Do you have any thoughts here?

**Comment by noahl** [comment]
@kholdaway yep, this is another instance of fact processing failing due to typing issues. I should start a list.

**Comment by deleeke** [comment]
@chambridge  I think this is related to a failure I was running into with our test machines that precipitated https://github.com/quipucords/camayoc/issues/228 . The trace back I find in the logs that seems to cause this deployment report not to be generated for the scan of the test machines `['sonar-wildfly-rhel-5-vc', 'sonar-wildfly-rhel-6-vc', 'sonar-wildfly-rhel-7-vc', 'sonar-jbossas-rhel-6-vc', 'sonar-jbossas-rhel-7-vc', 'sonar-jbossas-rhel-5-vc']` is this:

```
ERROR 2018-04-13 19:34:52,966 model 10639 140460447307520 Job 9 (inspect, elapsed_time: 281s) - STATE UPDATE (failed).  Additional State information: Fact collection 6 failed to be processed.
ERROR 2018-04-13 19:34:52,967 job 10639 140460447307520 KeyError:'1.6.0.Final'
Process ScanJobRunner-9:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/app/quipucords/scanner/job.py", line 113, in run
    self._send_facts_to_engine()
  File "/app/quipucords/scanner/job.py", line 196, in _send_facts_to_engine
    raise error
  File "/app/quipucords/scanner/job.py", line 179, in _send_facts_to_engine
    instance=fact_collection)
  File "/root/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/root/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/app/quipucords/fingerprinter/__init__.py", line 77, in process_fact_collection
    fingerprints_list = _process_sources(instance)
  File "/app/quipucords/fingerprinter/__init__.py", line 113, in _process_sources
    source)
  File "/app/quipucords/fingerprinter/__init__.py", line 282, in _process_source
    fingerprint = _process_network_fact(source, fact)
  File "/app/quipucords/fingerprinter/__init__.py", line 779, in _process_network_fact
    add_products_to_fingerprint(source, fact, fingerprint)
  File "/app/quipucords/fingerprinter/__init__.py", line 616, in add_products_to_fingerprint
    eap = detect_jboss_eap(source, raw_fact)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 329, in detect_jboss_eap
    new_presence = call_or_value(fact_dict[PRESENCE], fact_value)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 281, in call_or_value
    return obj(argument)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 195, in is_eap_manifest_version
    if 'EAP' in EAP_CLASSIFICATIONS[ver.strip()]:
KeyError: '1.6.0.Final'
```

If you want all the logs for this test run, I can send you a tarball!
