### ISSUE TITLE
BRMS produces key error in ansible post processing code

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1268]
## Specify type:
- Bug

### Priority:
- High
___

## Description:
Provide a description of the issue being raised.
```
RROR 2018-04-20 03:31:09,543 model 6043 139699599992576 Task 21 (inspect, network, 27ebe365-3ba2-401d-bd7e-8148b8a6b52b, elapsed_time: 1105s) - FAILED POST PROCESSING 10.10.181.72. Processor for jboss_brms_manifest_mf got value {'results': [{'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': '', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/standalone/deployments/business-central.war', '_ansible_item_result': True}, {'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': '', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/.installation/patches/jboss-eap-6.4.3.CP/misc/standalone/deployments/business-central.war', '_ansible_item_result': True}, {'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': '', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/standalone/deployments/decision-central.war', '_ansible_item_result': True}, {'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': '', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/.installation/patches/jboss-eap-6.4.3.CP/misc/standalone/deployments/decision-central.war', '_ansible_item_result': True}, {'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': 'mux_client_request_session: read from master failed: Broken pipe\r\n', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/standalone/deployments/kie-server.war', '_ansible_item_result': True}, {'unreachable': True, 'msg': 'Failed to connect to the host via ssh: ssh: connect to host 10.10.181.72 port 22: Connection timed out\r\n', 'item': '/opt/jboss/jboss-eap-6.4/.installation/patches/jboss-eap-6.4.3.CP/misc/standalone/deployments/kie-server.war', '_ansible_item_result': True}], 'changed': True, 'failed': True, 'msg': 'One or more items failed'}, returned Traceback (most recent call last):
  File "/app/quipucords/scanner/network/processing/process.py", line 134, in process
    processor_out = processor.process(fact_value)
  File "/app/quipucords/scanner/network/processing/brms.py", line 78, in process
    val = ProcessJbossBRMSManifestMF.process_item(item)
  File "/app/quipucords/scanner/network/processing/brms.py", line 62, in process_item
    if item['rc']:
KeyError: 'rc'
```
___

## Acceptance Criteria:
- [ ] Verify BRM does not error out while scanning

**Comment by noahl** [comment]
More details in the logs:
```
ERROR 2018-04-20 03:31:09,543 model 6043 139699599992576 Task 21 (inspect, network, 27ebe365-3ba2-401d-bd7e-8148b8a6b52b, elapsed_time: 1105s) - FAILED POST PROCESSING 10.10.181.72. Processor for jboss_brms_manifest_mf got value {'results': [{'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': '', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/standalone/deployments/business-central.war', '_ansible_item_result': True}, {'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': '', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/.installation/patches/jboss-eap-6.4.3.CP/misc/standalone/deployments/business-central.war', '_ansible_item_result': True}, {'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': '', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/standalone/deployments/decision-central.war', '_ansible_item_result': True}, {'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': '', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/.installation/patches/jboss-eap-6.4.3.CP/misc/standalone/deployments/decision-central.war', '_ansible_item_result': True}, {'rc': 124, 'stdout': '', 'stdout_lines': [], 'stderr': 'mux_client_request_session: read from master failed: Broken pipe\r\n', 'changed': True, '_ansible_no_log': False, 'failed': True, 'item': '/opt/jboss/jboss-eap-6.4/standalone/deployments/kie-server.war', '_ansible_item_result': True}, {'unreachable': True, 'msg': 'Failed to connect to the host via ssh: ssh: connect to host 10.10.181.72 port 22: Connection timed out\r\n', 'item': '/opt/jboss/jboss-eap-6.4/.installation/patches/jboss-eap-6.4.3.CP/misc/standalone/deployments/kie-server.war', '_ansible_item_result': True}], 'changed': True, 'failed': True, 'msg': 'One or more items failed'}, returned Traceback (most recent call last):
  File "/app/quipucords/scanner/network/processing/process.py", line 134, in process
    processor_out = processor.process(fact_value)
  File "/app/quipucords/scanner/network/processing/brms.py", line 78, in process
    val = ProcessJbossBRMSManifestMF.process_item(item)
  File "/app/quipucords/scanner/network/processing/brms.py", line 62, in process_item
    if item['rc']:
KeyError: 'rc'
```

**Comment by noahl** [comment]
Looks like the error is that I thought all Ansible results have an `rc` code, but unreachable results don't have them.

**Comment by kholdaway** [comment]
Gotcha.  Seems like an easy fix.
