### ISSUE TITLE
Attempting to alter unrelated credentials during scan fails because of database lock

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#1275]
## Specify type:
- Bug

### Priority:
- High
- Medium 
___

## Description:
During a scan, if the user attempts to create/update other unrelated resources, they encounter a 500 internal server error.

There are probably many ways this can happen, but I have created a script that reliably makes it happen on my local system. Previously we only saw this on our automation jobs for tests executing after the pause/cancel tests because of some trailing processes from a cancelled satellite scan.

This is a consequence of using SQLite.
___

### Version Information:
CLI: 
```
 qpc --version
0.0.42
```

Dev server at commit e73c1e53afabe61f065e050e372afd0efbb5965a 

### Expected behavior:
I can do unrelated tasks while a scan is in progress.

### Actual behavior:
I cannot do unrelated tasks reliably while a scan is in progress.

### Steps to reproduce:
Contact me for a satellite host name and the password for the "admin" credential.

PREREQS:

You will need to export the host name to the `$SATHOST` environment variable for this script to run correctly.
You need to have already configured the CLI's server settings and logged in.
You need to have the command line utility `uuidgen` installed and in your path. Alternatively, you could replace it with any other unique string generator.
You need to have a file that the server can find at `~/.ssh/id_rsa` or replace the path `$SSHKEY` is set to with one that is valid on the server.

Reproducer script:
```
#!/bin/bash

export SATCRED=$(uuidgen)
export SATSRC=$(uuidgen)
export SATSCN=$(uuidgen)
export SSHKEY=~/.ssh/id_rsa

# assuming a configured/logged in qpc client
echo "========================================================"
echo "This script assumes the qpc client is configured and"
echo "logged in. If that is not the case, abort now and start"
echo "over with a logged in client."
echo "========================================================"

sleep 2

echo "========================================================"
echo "Create a series of network credentials, unrelated to"
echo "the scan that will be run"
echo "========================================================"
for i in `seq 1 50`
do
	qpc cred add --type network --name foo$i --username bar --sshkey ~/.ssh/id_rsa
done

echo "========================================================"
echo "Provide the password for the satellite credential"
echo "========================================================"
qpc cred add --type satellite --name $SATCRED --username admin --password
qpc source add --type satellite --hosts $SATHOST --cred $SATCRED --name $SATSRC --ssl-cert-verify false

echo "========================================================"
echo "Create the scan and start it."
echo "========================================================"
qpc scan add --name $SATSCN --source $SATSRC
qpc scan start --name $SATSCN

echo "========================================================"
echo "Wait for a few seconds and then start trying to delete"
echo "the unrelated credentials while the scan is running."
echo "========================================================"

for i in `seq 1 10`
do 
	echo "${i}"
	sleep 1
done

echo "========================================================"
echo "Start trying to delete the network credentials."
echo "========================================================"

for i in `seq 1 50`
do 
	qpc cred clear --name foo$i && sleep 1
done

echo "========================================================"
echo "Clean up so we can reproduce this again."
echo "========================================================"

qpc scan clear --all
qpc source clear --all
qpc cred clear --all
```

Sample output:
```
========================================================
This script assumes the qpc client is configured and
logged in. If that is not the case, abort now and start
over with a logged in client.
========================================================
========================================================
Create a series of network credentials, unrelated to
the scan that will be run
========================================================
Credential "foo1" was added.
Credential "foo2" was added.
Credential "foo3" was added.
Credential "foo4" was added.
Credential "foo5" was added.
Credential "foo6" was added.
Credential "foo7" was added.
Credential "foo8" was added.
Credential "foo9" was added.
Credential "foo10" was added.
Credential "foo11" was added.
Credential "foo12" was added.
Credential "foo13" was added.
Credential "foo14" was added.
Credential "foo15" was added.
Credential "foo16" was added.
Credential "foo17" was added.
Credential "foo18" was added.
Credential "foo19" was added.
Credential "foo20" was added.
Credential "foo21" was added.
Credential "foo22" was added.
Credential "foo23" was added.
Credential "foo24" was added.
Credential "foo25" was added.
Credential "foo26" was added.
Credential "foo27" was added.
Credential "foo28" was added.
Credential "foo29" was added.
Credential "foo30" was added.
Credential "foo31" was added.
Credential "foo32" was added.
Credential "foo33" was added.
Credential "foo34" was added.
Credential "foo35" was added.
Credential "foo36" was added.
Credential "foo37" was added.
Credential "foo38" was added.
Credential "foo39" was added.
Credential "foo40" was added.
Credential "foo41" was added.
Credential "foo42" was added.
Credential "foo43" was added.
Credential "foo44" was added.
Credential "foo45" was added.
Credential "foo46" was added.
Credential "foo47" was added.
Credential "foo48" was added.
Credential "foo49" was added.
Credential "foo50" was added.
========================================================
Provide the password for the satellite credential
========================================================
Provide a connection password.
Password: 
Credential "7f8b8b5f-6d5f-4469-9cf6-98281a195854" was added.
Source "c924352c-8817-46d7-8245-c28e87ae8197" was added.
========================================================
Create the scan and start it.
========================================================
Scan "8f809264-ae04-4f6a-92b3-18af1c4a04ae" was added.
Scan "7" started.
========================================================
Wait for a few seconds and then start trying to delete
the unrelated credentials while the scan is running.
========================================================
1
2
3
4
5
6
7
8
9
10
========================================================
Start trying to delete the network credentials.
========================================================
Credential "foo1" was removed.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
Credential "foo5" was removed.
Credential "foo6" was removed.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
Credential "foo10" was removed.
Credential "foo11" was removed.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
Credential "foo16" was removed.
Credential "foo17" was removed.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
Credential "foo21" was removed.
Credential "foo22" was removed.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
Credential "foo26" was removed.
Credential "foo27" was removed.
Credential "foo28" was removed.
Credential "foo29" was removed.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
Credential "foo35" was removed.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
Credential "foo39" was removed.
Credential "foo40" was removed.
Credential "foo41" was removed.
Credential "foo42" was removed.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
An internal server error occurred. For more information, see the server log file.
Credential "foo46" was removed.
An internal server error occurred. For more information, see the server log file.
Credential "foo48" was removed.
Credential "foo49" was removed.
An internal server error occurred. For more information, see the server log file.
========================================================
Clean up so we can reproduce this again.
========================================================
All scans were removed.
All sources were removed.
All credentials were removed.

```
### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora            | 26        | 3.6            | Bare Metal
Target System   | Satellite 6             | n/a        | n/a          | n/a

**Comment by kdelee** [comment]
Sample from logs:
```
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas77. Stats: systems_count=325, systems_scanned=285, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas78. Stats: systems_count=325, systems_scanned=286, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas79. Stats: systems_count=325, systems_scanned=287, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas8. Stats: systems_count=325, systems_scanned=288, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas80. Stats: systems_count=325, systems_scanned=289, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas81. Stats: systems_count=325, systems_scanned=290, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas82. Stats: systems_count=325, systems_scanned=291, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas83. Stats: systems_count=325, systems_scanned=292, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas84. Stats: systems_count=325, systems_scanned=293, systems_failed=0, systems_unreachable=0
INFO "GET /api/v1/credentials/?name=foo49 HTTP/1.1" 200 201
ERROR Internal Server Error: /api/v1/credentials/398/
Traceback (most recent call last):
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/elijah/sfw/quipu/quipucords/quipucords/api/credential/view.py", line 194, in destroy
    cred.delete()
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/models/base.py", line 973, in delete
    return collector.delete()
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/models/deletion.py", line 284, in delete
    count = qs._raw_delete(using=self.using)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/models/query.py", line 631, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/models/sql/subqueries.py", line 80, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/elijah/envs/quipucords/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas85. Stats: systems_count=325, systems_scanned=294, systems_failed=0, systems_unreachable=0
ERROR "DELETE /api/v1/credentials/398/ HTTP/1.1" 500 23536
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas86. Stats: systems_count=325, systems_scanned=295, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas87. Stats: systems_count=325, systems_scanned=296, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 56s) - PROCESSING sthirugnkansas88. Stats: systems_count=325, systems_scanned=297, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 57s) - PROCESSING sthirugnkansas89. Stats: systems_count=325, systems_scanned=298, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 57s) - PROCESSING sthirugnkansas9. Stats: systems_count=325, systems_scanned=299, systems_failed=0, systems_unreachable=0
INFO Task 16 (inspect, satellite, 7b2d6ff6-6d4a-42e5-864c-c9075e4a9cf7, elapsed_time: 57s) - PROCESSING sthirugnkansas90. Stats: systems_count=325, systems_scanned=300, systems_failed=0, systems_unreachable=0

```

**Comment by kholdaway** [comment]
SQLite is a file.  So a lock is for the db not a table.  See http://sqlite.1065341.n5.nabble.com/Sqlite-lock-granularity-td74558.html

**Comment by kholdaway** [comment]
Based on conversations with Dan, we are going to hold off fixing these for now.

**Comment by kholdaway** [comment]
Yep. Glad you did.

**Comment by kholdaway** [comment]
Keeping this open as a duplicate of https://github.com/quipucords/quipucords/issues/1410.  Once https://github.com/quipucords/quipucords/issues/1410 is complete, we can verify that this problem goes away.
