### ISSUE TITLE
Satellite scan job is not being updated if the connect task fails because SSL

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#1533]
## Bug Description:
The scan job status is not being updated when a satellite connect task fail because SSL.

### Expected behavior:
The scan job should be resilient and state any issue it founds. Also it should update the status to reflect the job is not running anymore.

### Actual behavior:
The job status is not updated, even though the logs state the job has been completed.

This is the qpc output:

```
$ qpc scan job --id 4
{
    "id": 4,
    "options": {
        "max_concurrency": 50
    },
    "scan": {
        "id": 4,
        "name": "sat6-try2"
    },
    "scan_type": "inspect",
    "sources": [
        {
            "id": 5,
            "name": "sat6",
            "source_type": "satellite"
        }
    ],
    "start_time": "2018-09-28T14:44:35.839911",
    "status": "running",
    "status_message": "Job is running.",
    "systems_count": 0,
    "systems_failed": 0,
    "systems_scanned": 0,
    "systems_unreachable": 0,
    "tasks": [
        {
            "scan_type": "connect",
            "source": 5,
            "start_time": "2018-09-28T14:44:35.884167",
            "status": "running",
            "status_message": "Task is running."
        },
        {
            "scan_type": "inspect",
            "source": 5,
            "status": "pending",
            "status_message": "Task is pending."
        }
    ]
}
```

And this is the related server log:

```
INFO Job 4 (inspect, elapsed_time: 0s) - STATE UPDATE (running)
INFO Job 4 (inspect, elapsed_time: 0s) - Queuing the following incomplete tasks: 11, 12
INFO Task 11 (connect, satellite, sat6, elapsed_time: 0s) - STATE UPDATE (running)
INFO Task 11 (connect, satellite, sat6, elapsed_time: 0s) - Satellite 5 status check endpoint not found. Attempting Satellite 6.
ERROR Task 11 (connect, satellite, sat6, elapsed_time: 1s) - Satellite connect error encountered: HTTPSConnectionPool(host='sat-r220-07.lab.eng.rdu2.redhat.com', port=443): Max retries exceeded with url: /api/status (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:866)'),)). Connect scan failed for source sat6.
Process ScanJobRunner-4:
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(256)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/elyezer/code/quipucords/quipucords/scanner/job.py", line 123, in run
    runner.scan_task.fail(status_message)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/elyezer/code/quipucords/quipucords/api/scantask/model.py", line 364, in fail
    self.save()
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/models/base.py", line 904, in _save_table
    forced_update)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/models/base.py", line 954, in _do_update
    return filtered._update(values) > 0
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/models/query.py", line 664, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1199, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/elyezer/.virtualenvs/quipucords/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(256)

INFO Job 4 (inspect, elapsed_time: 0s) - SCAN JOB MANAGER: scan job has completed.
```

### Steps to reproduce:
Try to scan a satellite that has self signed SSL certificate with SSL verify enabled and watch the logs.

These are the command I ran:

```console
$ qpc cred add --name sat6 --type satellite --password --username admin
$ qpc source add --name sat6 --type satellite --hosts sat-server.example.com --cred sat6
$ qpc scan add --name sat6 --source sat6
$ qpc scan start --name sat6
$ qpc scan job --id <job-id>
```
___

## Acceptance Criteria:

- [ ] Scan job should be resilient to task failures and state why it was failed
- [ ] Scan job should update its status if any of its tasks fail.

___

### Version Information:
Commit a977aec516a8755e1e58dfccf4178a336673c330

**Comment by elyezer** [comment]
This is related to https://github.com/quipucords/quipucords/issues/1531 but with a better way to reproduce. As you can see if an exception is raised the job status is not properly updated and it should.

**Comment by kholdaway** [comment]
Looks like a simple fix.  We should use a TextField for some of these long values.

**Comment by kholdaway** [comment]
Also, fixed by changing ScanJob.status_message to a TextField.
