### ISSUE TITLE
Upgrade of QPC container fails because ansible value password is regenerated

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1667]
## Bug Description:
When a new container is launched, the ansible value password is generated.  Problem is that a newly released QPC version will not have that and generate a new password.  The impact is that all creds stored in the QPC db cannot be decrypted.

The solution to ensure that the ansible value is mapped to a volume so it is not reset.

### Expected behavior:
Upgraded creds work

### Actual behavior:
After upgrade creds cannot be decrypted

### Steps to reproduce:
Run a scan in a docker container and then rebuild the docker container and try to rescan.

___

## Acceptance Criteria:

- [ ] Scans can be run with a cred from a previous docker container

**Comment by kholdaway** [comment]
This doesn't work for rhel 7
```
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/root/venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/root/venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/venv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/venv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/root/venv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/venv/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/app/quipucords/quipucords/wsgi.py", line 28, in <module>
    application = get_wsgi_application()
  File "/root/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/venv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/root/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/root/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/root/venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/quipucords/quipucords/settings.py", line 86, in <module>
    with open(DJANGO_SECRET_PATH, 'w') as secret_file:
PermissionError: [Errno 13] Permission denied: '/var/data/secret_vault/secret.txt'
```
