### ISSUE TITLE
qpc restart scanjob fails after pause

### ISSUE THREAD

**Issue by himmAllRight** [quipucords/quipucords#2040]
## Bug Description:
When a scan is paused but then restarted, the scanjob fails unexpectedly. Viewing the logs, it appears that it fails because it hits a `NoneType` value.

Error in quipucords.log:
```
INFO 2020-01-30 21:16:05,865 model 31 140422052558592 Job 220, Task 3 of 3 (fingerprint, details_report=None, elapsed_time: 0s) - STATE UPDATE (paused)
INFO 2020-01-30 21:16:05,866 model 31 140422052558592 Job 220 (inspect, elapsed_time: 9s) - STATE UPDATE (paused)
INFO 2020-01-30 21:16:06,552 model 27 140422052558592 Job 220 (inspect, elapsed_time: 0s) - SCAN JOB MANAGER: Process successfully terminated.
192.168.122.45 - - [30/Jan/2020:21:16:07 +0000] "GET /api/v1/jobs/220/ HTTP/1.1" 200 1062 "-" "python-requests/2.20.0"
INFO 2020-01-30 21:16:11,558 manager 27 140422052558592 SCAN JOB MANAGER: Loading scan job 220.
INFO 2020-01-30 21:16:11,565 manager 27 140422052558592 SCAN JOB MANAGER: Currently running scan job 220.  Scan queue length is 0. Queued jobs: []
INFO 2020-01-30 21:16:11,592 model 192 140422052558592 Job 220 (inspect, elapsed_time: 0s) - STATE UPDATE (running)
INFO 2020-01-30 21:16:11,595 model 192 140422052558592 Job 220 (inspect, elapsed_time: 0s) - Job has 0 remaining tasks
Process ScanJobRunner-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/app/quipucords/scanner/job.py", line 109, in run
    details_report = fingerprint_task_runner.scan_task.details_report
AttributeError: 'NoneType' object has no attribute 'scan_task'
192.168.122.45 - - [30/Jan/2020:21:16:12 +0000] "GET /api/v1/jobs/220/ HTTP/1.1" 200 1064 "-" "python-requests/2.20.0"
INFO 2020-01-30 21:16:16,579 model 27 140422052558592 Job 220 (inspect, elapsed_time: 5s) - SCAN JOB MANAGER: scan job has unexpectedly failed.
ERROR 2020-01-30 21:16:16,580 model 27 140422052558592 Job 220 (inspect, elapsed_time: 5s) - Scan manager failed job due to unexpected error.
INFO 2020-01-30 21:16:16,614 model 27 140422052558592 Job 220 (inspect, elapsed_time: 5s) - FAILURE STATS. Stats: systems_count=1, systems_scanned=0, systems_failed=0, systems_unreachable=0, system_fingerprint_count=0
ERROR 2020-01-30 21:16:16,614 model 27 140422052558592 Job 220 (inspect, elapsed_time: 5s) - STATE UPDATE (failed).  Additional State information: Scan manager failed job due to unexpected error.
192.168.122.45 - - [30/Jan/2020:21:16:18 +0000] "GET /api/v1/jobs/220/ HTTP/1.1" 200 1136 "-" "python-requests/2.20.0"
```

### Expected behavior:
When a scanjob is paused, running a `qpc scan restart` should un-pause and start/restart it successfully.

### Actual behavior:
When restarting a paused scan, it fails due to an unexpected error.

### Steps to reproduce:
- Start a scan
- Pause the scan
- Restart the scan (note: `restart` not `start`)

___

## Acceptance Criteria:

- [ ] `qpc scan restart` should successfully restart a paused scan

CLI version, server version or git commit information.

### Environment information:

Version Information:

Node OS: rhel8-os

QPC-Tools: 0.2.4

Quipucords Version: 0.9.2

QPC: 0.9.3

Podman: podman-1.4.2-6
Environment information:

The Jenkisn testing pipeline, using a rhel8-os node. Also, reproduced inside a local RHEL8 VM, scanning the test machines.

**Comment by gtanzillo** [comment]
This is tracked on 1.x eng roadmap
