### ISSUE TITLE
QPC Scan fails for satellite - TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by ktenzer** [quipucords/quipucords#2046]
## Bug Description:
When using Satellite as a source, scan fails with error that it is unable to generate a deployment report. The logs have this error.

```
Process ScanJobRunner-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/app/quipucords/scanner/job.py", line 137, in run
    raise error
  File "/app/quipucords/scanner/job.py", line 129, in run
    task_status = self._run_task(fingerprint_task_runner)
  File "/app/quipucords/scanner/job.py", line 212, in _run_task
    raise error
  File "/app/quipucords/scanner/job.py", line 196, in _run_task
    self.manager_interrupt)
  File "/app/quipucords/fingerprinter/task.py", line 274, in run
    raise error
  File "/app/quipucords/fingerprinter/task.py", line 250, in run
    manager_interrupt, details_report)
  File "/app/quipucords/fingerprinter/task.py", line 289, in _process_details_report
    fingerprints_list = self._process_sources(details_report)
  File "/app/quipucords/fingerprinter/task.py", line 509, in _process_sources
    source_fingerprints = self._process_source(source)
  File "/app/quipucords/fingerprinter/task.py", line 717, in _process_source
    fingerprint = self._process_satellite_fact(source, fact)
  File "/app/quipucords/fingerprinter/task.py", line 1552, in _process_satellite_fact
    self._add_products_to_fingerprint(source, fact, fingerprint)
  File "/app/quipucords/fingerprinter/task.py", line 1109, in _add_products_to_fingerprint
    eap = detect_jboss_eap(source, raw_fact)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 386, in detect_jboss_eap
    new_presence = call_or_value(fact_dict[PRESENCE], fact_value)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 318, in call_or_value
    return obj(argument)
  File "/app/quipucords/fingerprinter/jboss_eap.py", line 166, in find_eap_entitlement
    if product_entitlement_found(entitlements, PRODUCT):
  File "/app/quipucords/fingerprinter/utils.py", line 28, in product_entitlement_found
    if product_name in name:
TypeError: argument of type 'NoneType' is not iterable
INFO 2020-05-11 22:15:58,562 manager 27 140496786917120 SCAN JOB MANAGER: Currently running scan job 5.  Scan queue length is 0. Queued jobs: []
INFO 2020-05-11 22:16:00,169 model 27 140496814745344 Job 5 (inspect, elapsed_time: 295s) - SCAN JOB MANAGER: scan job has completed.
10.150.42.0 - - [11/May/2020:22:16:21
```
### Expected behavior:
Deployment report and scan complete successfully

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
1) Create source and connect to satellite
2) Run scan
3) Scan fails no report can be downloaded

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

### Version Information:
version 0.9.2

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.6        | 3.6            | VM
Target System   | Satellite Server | 6.5        | ?          | VM

**Comment by kholdaway** [comment]
Fixed in master with https://github.com/quipucords/quipucords/pull/2047
