### ISSUE TITLE
Socket Error Processing Request

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2079]
## Bug Description:

[ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = six.next(parser)
  File "/usr/lib/python3.6/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/usr/lib/python3.6/site-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/usr/lib/python3.6/site-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/usr/lib/python3.6/site-packages/gunicorn/http/message.py", line 193, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/lib/python3.6/site-packages/gunicorn/http/message.py", line 184, in get_data
    data = unreader.read()
  File "/usr/lib/python3.6/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/usr/lib/python3.6/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/lib64/python3.6/ssl.py", line 956, in recv
    return self.read(buflen)
  File "/usr/lib64/python3.6/ssl.py", line 833, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 592, in read
    v = self._sslobj.read(len)
OSError: [Errno 0] Error

### Expected behavior:
No error

### Actual behavior:
socket error

### Steps to reproduce:
unclear

___

## Acceptance Criteria:

Define workaround and fix issue.

___

### Version Information:
https://people.redhat.com/~jkreft/rhel-discovery-iso.tar.gz

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Not Available

**Comment by gtanzillo** [comment]
This is tracked on 1.x eng roadmap
