### ISSUE TITLE
Sat6 scan dies but continues to report as "running"

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#569]
## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
While scanning a satellite system (that has completed before, but not this time), some situation arises that causes the following exception to occur:

```
Process ScanJobRunner-15:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/elijah/sfw/quipu/quipucords/quipucords/scanner/job.py", line 80, in run
    status_message, task_status = runner.run()
  File "/home/elijah/sfw/quipu/quipucords/quipucords/scanner/satellite/inspect.py", line 95, in run
    api.hosts_facts()
  File "/home/elijah/sfw/quipu/quipucords/quipucords/scanner/satellite/six.py", line 532, in hosts_facts
    self.host_details(host.get(ID), host.get(NAME))
  File "/home/elijah/sfw/quipu/quipucords/quipucords/scanner/satellite/six.py", line 501, in host_details
    None, host_id))
  File "/home/elijah/sfw/quipu/quipucords/quipucords/scanner/satellite/six.py", line 208, in host_fields
    for key in facts:
TypeError: 'NoneType' object is not iterable

```

Reading the logs, it appears that the scan task halts and does not resume. The server is still alive and responds to GET requests inquiring about the status of the scan. It claims that the scan is "running" but it is actually dead.
___

### Expected behavior:
If a scan breaks, it should report as failed.
Also, if facts are not available for a single part of the scan, the scan should proceed and collect whatever information it can.

### Actual behavior:
 All collected data was lost and the scan broken due to this exception. Additionally, the server did not know that the scan was broken and continued to report it as running.

### Steps to reproduce:
I don't have a clear reproducer because I have scanned this satellite before to completion. Contact me directly for logs of the event and for what satellite I was using.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | FEDORA             | 26        | 3.6            | Bare Metal
Target System   | Satellite 6.2             | n/a        | n/a          | n/a

**Comment by kdelee** [comment]
Good news is it appears other scans can be started and proceed even with this once reporting being hung in the "running" state
