### ISSUE TITLE
Docker build fails part of the way through

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#686]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High'ish

## Description:
To help speed up UI development the UI team has been foregoing a Python compile and instead has been running the Docker compile for demo purposes.

It appears a question gets asked during the Docker build that appears to interrupt the process and it fails... ```Did you rename credential.sudo_password to credential.become_password (a CharField)? [y/N]```

### Expected behavior:
Docker build to work without interrupts.

### Actual behavior:
The Docker build fails when it gets to the point...
```shell
...
Removing intermediate container a3c957e54136
Step 40/44 : RUN . ~/venv/bin/activate;make server-init server-static
 ---> Running in c434344c3d20
/root/venv/bin/python quipucords/manage.py makemigrations api --settings quipucords.settings
Did you rename credential.sudo_password to credential.become_password (a CharField)? [y/N] Traceback (most recent call last):
  File "quipucords/manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/root/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/venv/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 177, in handle
    migration_name=self.migration_name,
  File "/root/venv/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 47, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/root/venv/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 186, in _detect_changes
    self.generate_renamed_fields()
  File "/root/venv/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 808, in generate_renamed_fields
    if self.questioner.ask_rename(model_name, rem_field_name, field_name, field):
  File "/root/venv/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 197, in ask_rename
    field_instance.__class__.__name__), False)
  File "/root/venv/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 88, in _boolean_input
    result = input("%s " % question)
EOFError: EOF when reading a line
make: *** [Makefile:64: server-makemigrations] Error 1
...
```

### Steps to reproduce:
1. Open terminal, change directories into the repo, and
2. OPTIONAL: Clean up and wipe the image
    ```shell
    $ docker system prune
    $ docker rmi [IMAGE ID]
    ```
3. From the root Quipucords directory run
    ```shell
      $ docker -D build . -t quipucords:latest
    ```

### Environment information:
Mac OSX

**Comment by kdelee** [comment]
Have you run `make clean` after pulling in new changes and before initiating the container build?

**Comment by cdcabrera** [comment]
Solved @kdelee ! Shutting this issue down
